//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstXP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artwork
    {
        public int artworkId { get; set; }
        public string artistName { get; set; }
        public string name { get; set; }
        public string year { get; set; }
        public double height { get; set; }
        public double width { get; set; }
        public string location { get; set; }
        public string imageName { get; set; }
    }
}
