//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstXP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public int AuctionId { get; set; }
        public double startingBid { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string itemText { get; set; }
    
        public virtual Artwork Artwork { get; set; }
    }
}
